clusterGroupName: tap-vcf
gitrepo: ssh://git@gitserver.example.com:/home/git/tmc-tap-vcf.git
clusters:
  site1-tap-run:
    mgmt_cluster: cluster01-wcp
    name: site1-tap-run
    provisioner: site1-tap
    cp_count: 1
    worker_count: 3
    worker_vm_class: best-effort-large
    cp_vm_class: best-effort-large
    storage_class: my-storage-policy
    k8s_version: v1.26.5+vmware.2-fips.1-tkg.1
    kubelet_storage: 100G
    containerd_storage: 100G
    ntp: 10.0.0.1
  site2-tap-run:
    mgmt_cluster: cluster01-wcp
    name: site2-tap-run
    provisioner: site2-tap
    cp_count: 1
    worker_count: 3
    worker_vm_class: best-effort-large
    cp_vm_class: best-effort-large
    storage_class: my-storage-policy
    k8s_version: v1.26.5+vmware.2-fips.1-tkg.1
    kubelet_storage: 100G
    containerd_storage: 100G
    ntp: 10.0.0.1