---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-apps-pre
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m
  path: ./flux/apps/clustergroups/tap-vcf/pre
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-base

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-apps-post
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m
  path: ./flux/apps/clustergroups/tap-vcf/post
  prune: true
  dependsOn:
    - name: group-apps-pre
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-base